### ISSUE TITLE
Error loading links after more than 24 are added

### ISSUE THREAD

**Issue by prestonzen** [ccbikai/Sink#92]
Uncaught (in promise) FetchError: [GET] "/api/link/list?limit=24&cursor": 500 
    at async o (B9ekPmBX.js:18:21972)
    at async a (B9ekPmBX.js:18:22025)
    at async h (CUBK5xjm.js:6:644)
    at async Promise.all (index 0)

**Comment by xinshoutw** [comment]
Is it the same issue?
https://github.com/ccbikai/Sink/issues/90#issue-2724833715

**Comment by xinshoutw** [comment]
Duplicate of #90

**Comment by ccbikai** [comment]
Update code, refer to the official GitHub documentation [Syncing a fork branch from the web UI](https://docs.github.com/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork#syncing-a-fork-branch-from-the-web-ui).
